name: publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.7.2
    
      - name: Restore
        run: dotnet restore ./PlanetFinder.sln
      
      - name: Build
        run: dotnet build ./PlanetFinder.sln --configuration Release --no-restore
      
      - name: Publish
        run: dotnet publish ./PlanetFinder.sln --configuration Release --no-build
